### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by qigaowei** [liuanxin/api-document#7]
### 使用版本:
请告知引用的版本(请先用 latest 版本重试)
0.9.0

### 报错信息
```
请给出错误信息
```
[TID: N/A] 2024-04-17 17:55:23.836 [http-nio-9604-exec-10] ERROR c.z.h.n.c.a.c.GlobalException - [other,121] - 未知异常
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.github.liuanxin.api.util.ReturnHandler.returnInfo(ReturnHandler.java:201)
	at com.github.liuanxin.api.util.ReturnHandler.handlerReturn(ReturnHandler.java:145)
	at com.github.liuanxin.api.util.ReturnHandler.handlerReturn(ReturnHandler.java:39)
	at com.github.liuanxin.api.util.WebUtil.infoAndUrlMap(WebUtil.java:120)
	at com.github.liuanxin.api.web.DocumentController.collect(DocumentController.java:87)
	at com.github.liuanxin.api.web.DocumentController.getUrlInfo(DocumentController.java:77)

### 希望结果
请告知预期

### 复现步骤
请告知出现错误时的整个上下文, 如果复现很复杂, 请将 demo 传到 github 并留下地址

**Comment by liuanxin** [comment]
当响应实体中只用了 `List` 但没有指定具体的泛型类型(比如 `List<String>`  `List<XX>` 就正常)时, 就会出现这个问题, 0.9.1 版本已修复, 请更新版本. @qigaowei
